### ISSUE TITLE
Is there a way to set variables depending on choices?

### ISSUE THREAD

**Issue by Judahh** [benknoble/tmplr#16]
Is there a way to programatically read a var? 
something like:
```yaml
- read: database_type
    prompt: What database type do you want to use?
    choices:
      - MongoDB
      - PGSQL
      - MSSQL

  - if: database_type == 'MongoDB'
    read: database_var
    eval: "const database = new MongoPersistence(readDatabase, {\n\tsample: new SampleSchema(),\n});"
    else:
      read: database_var
      eval: "const database = new DAOPersistence(sql, {\n\tsample: new SampleDAO(),\n});"

  - if: database_type == 'PGSQL'
    steps:
      - read: database_import
        eval: "import { PGSQL } from '@flexiblepersistence/pgsql';\nimport SampleDAO from './dAOs/sampleDAO';"
      - read: database_sql
        eval: "const sql = new PGSQL(readDatabase);"
    else:
      if: database_type == 'MSSQL'
      steps:
      - read: database_import
        eval: "import { MSSQL } from '@flexiblepersistence/mssql';\nimport SampleDAO from './dAOs/sampleDAO';"
      - read: database_sql
        eval: "const sql = new MSSQL(readDatabase);"
      else:
        steps:
          - read: database_import
            eval: "import SampleSchema from './schemas/sampleSchema';"
          - read: database_sql
            eval: ""
```
